### PR TITLE
#3 - Creates Level-2

### PR DESCRIPTION
**Pull request by Palash3101**
## Overview

1. This PR fixes or fixes part of #3 .
2. This PR does the following: Creates level-2, according to the given Description and Game Mechanics. There are two parts, that can be used according to the narrative.
3. A README File has been added for the Player moves and mechanics.

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [ ] The PR is made from a branch that's **not** called "main/master".

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by Captain-T2004** [comment]
@Palash3101, Please add some instructions to your level(like basic controls or a text msg to explain the mechanics). Everything thing else looks good to me.

**Comment by Palash3101** [comment]
> @Palash3101, Please add some instructions to your level(like basic controls or a text msg to explain the mechanics). Everything thing else looks good to me.

Okay wilco,
Do you want the control instructions on both, or just the first simpler one.
As for level instructions I'll put signs, to make the game flow a bit more clearer.

**Comment by Captain-T2004** [comment]
Your choice if the mechanisms remains the same for both parts then only putting instructions on the first part will be enough.

**Comment by Palash3101** [comment]
I have commited and pushed the required changes. What is the next step...

**Comment by Captain-T2004** [comment]
Ok. LGTM, so I'm merging it. @Palash3101, I am adding 2 new issues regarding the pause menu and start menu in next 10 mins, pick whichever one you like and start working on that. Thank you.

**Pull request merged**
